package com.nines.nutsfact.infrastructure.converter;

import com.nines.nutsfact.api.v1.request.FoodRawMaterialRequest;
import com.nines.nutsfact.domain.model.FoodRawMaterial;
import com.nines.nutsfact.domain.model.nutrition.NutritionBasic;
import com.nines.nutsfact.domain.model.nutrition.NutritionMinerals;
import com.nines.nutsfact.domain.model.nutrition.NutritionVitamins;
import org.springframework.stereotype.Component;

/**
 * 原材料のRequest⇔Entity変換
 */
@Component
public class FoodRawMaterialConverter {

    public FoodRawMaterial toEntity(FoodRawMaterialRequest request) {
        if (request == null) {
            return null;
        }

        NutritionBasic basicNutrition = NutritionBasic.builder()
            .refuse(request.getRefuse())
            .refuseFlag(request.getRefuseFlag())
            .enerc(request.getEnerc())
            .enercFlag(request.getEnercFlag())
            .enercKcal(request.getEnercKcal())
            .enercKcalFlag(request.getEnercKcalFlag())
            .water(request.getWater())
            .waterFlag(request.getWaterFlag())
            .prot(request.getProt())
            .protFlag(request.getProtFlag())
            .protcaa(request.getProtcaa())
            .protcaaFlag(request.getProtcaaFlag())
            .fat(request.getFat())
            .fatFlag(request.getFatFlag())
            .fatnlea(request.getFatnlea())
            .fatnleaFlag(request.getFatnleaFlag())
            .chole(request.getChole())
            .choleFlag(request.getCholeFlag())
            .chocdf(request.getChocdf())
            .chocdfFlag(request.getChocdfFlag())
            .choavlm(request.getChoavlm())
            .choavlmFlag(request.getChoavlmFlag())
            .choavlmMark(request.getChoavlmMark())
            .choavl(request.getChoavl())
            .choavlFlag(request.getChoavlFlag())
            .choavldf(request.getChoavldf())
            .choavldfFlag(request.getChoavldfFlag())
            .choavldfMark(request.getChoavldfMark())
            .fib(request.getFib())
            .fibFlag(request.getFibFlag())
            .polyl(request.getPolyl())
            .polylFlag(request.getPolylFlag())
            .oa(request.getOa())
            .oaFlag(request.getOaFlag())
            .ash(request.getAsh())
            .ashFlag(request.getAshFlag())
            .alc(request.getAlc())
            .alcFlag(request.getAlcFlag())
            .naclEq(request.getNaclEq())
            .naclEqFlag(request.getNaclEqFlag())
            .build();

        NutritionMinerals minerals = NutritionMinerals.builder()
            .na(request.getNa())
            .naFlag(request.getNaFlag())
            .k(request.getK())
            .kFlag(request.getKFlag())
            .ca(request.getCa())
            .caFlag(request.getCaFlag())
            .mg(request.getMg())
            .mgFlag(request.getMgFlag())
            .p(request.getP())
            .pFlag(request.getPFlag())
            .fe(request.getFe())
            .feFlag(request.getFeFlag())
            .zn(request.getZn())
            .znFlag(request.getZnFlag())
            .cu(request.getCu())
            .cuFlag(request.getCuFlag())
            .mn(request.getMn())
            .mnFlag(request.getMnFlag())
            .idd(request.getIdd())
            .iddFlag(request.getIddFlag())
            .se(request.getSe())
            .seFlag(request.getSeFlag())
            .cr(request.getCr())
            .crFlag(request.getCrFlag())
            .mo(request.getMo())
            .moFlag(request.getMoFlag())
            .build();

        NutritionVitamins vitamins = NutritionVitamins.builder()
            .ret(request.getRet())
            .retFlag(request.getRetFlag())
            .carta(request.getCarta())
            .cartaFlag(request.getCartaFlag())
            .cartb(request.getCartb())
            .cartbFlag(request.getCartbFlag())
            .crypxb(request.getCrypxb())
            .crypxbFlag(request.getCrypxbFlag())
            .cartbeq(request.getCartbeq())
            .cartbeqFlag(request.getCartbeqFlag())
            .vitaRae(request.getVitaRae())
            .vitaRaeFlag(request.getVitaRaeFlag())
            .vitd(request.getVitd())
            .vitdFlag(request.getVitdFlag())
            .tocpha(request.getTocpha())
            .tocphaFlag(request.getTocphaFlag())
            .tocphb(request.getTocphb())
            .tocphbFlag(request.getTocphbFlag())
            .tocphg(request.getTocphg())
            .tocphgFlag(request.getTocphgFlag())
            .tocphd(request.getTocphd())
            .tocphdFlag(request.getTocphdFlag())
            .vitk(request.getVitk())
            .vitkFlag(request.getVitkFlag())
            .thia(request.getThia())
            .thiaFlag(request.getThiaFlag())
            .ribf(request.getRibf())
            .ribfFlag(request.getRibfFlag())
            .nia(request.getNia())
            .niaFlag(request.getNiaFlag())
            .niac(request.getNiac())
            .niacFlag(request.getNiacFlag())
            .vitb6a(request.getVitb6a())
            .vitb6aFlag(request.getVitb6aFlag())
            .vitb12(request.getVitb12())
            .vitb12Flag(request.getVitb12Flag())
            .fol(request.getFol())
            .folFlag(request.getFolFlag())
            .pantac(request.getPantac())
            .pantacFlag(request.getPantacFlag())
            .biot(request.getBiot())
            .biotFlag(request.getBiotFlag())
            .vitc(request.getVitc())
            .vitcFlag(request.getVitcFlag())
            .build();

        return FoodRawMaterial.builder()
            .foodId(request.getFoodId())
            .foodNo(request.getFoodNo())
            .foodGroupId(request.getFoodGroupId())
            .indexNo(request.getIndexNo())
            .classCategoryId(request.getClassCategoryId())
            .originalFoodId(request.getOriginalFoodId())
            .originalFoodGroupId(request.getOriginalFoodGroupId())
            .originalFoodNo(request.getOriginalFoodNo())
            .originalIndexNo(request.getOriginalIndexNo())
            .originalFoodName(request.getOriginalFoodName())
            .foodName(request.getFoodName())
            .foodFukuBunrui(request.getFoodFukuBunrui())
            .foodRuiKubun(request.getFoodRuiKubun())
            .foodDaiBunrui(request.getFoodDaiBunrui())
            .foodCyuBunrui(request.getFoodCyuBunrui())
            .foodSyoBunrui(request.getFoodSyoBunrui())
            .foodSaibun(request.getFoodSaibun())
            .categoryId(request.getCategoryId())
            .hashtag(request.getHashtag())
            .compositeRawMaterialsKb(request.getCompositeRawMaterialsKb())
            .pricePerUnit(request.getPricePerUnit())
            .makerId(request.getMakerId())
            .sellerId(request.getSellerId())
            .compositeRawItemlist(request.getCompositeRawItemlist())
            .displayName(request.getDisplayName())
            .placeOfOrigin(request.getPlaceOfOrigin())
            .displayPlaceOfOrigin(request.getDisplayPlaceOfOrigin())
            .revisionOfFoodNo(request.getRevisionOfFoodNo())
            .nextFoodId(request.getNextFoodId())
            .expireDate(request.getExpireDate())
            .status(request.getStatus())
            .updateInformation(request.getUpdateInformation())
            .description(request.getDescription())
            .descriptionFlag(request.getDescriptionFlag())
            .isActive(request.getIsActive())
            .basicNutrition(basicNutrition)
            .minerals(minerals)
            .vitamins(vitamins)
            .build();
    }
}
